const assert = require('node:assert/strict');
const lz4 = require('lz4js');
const xxhash = require('lz4js/xxh32');
const decompress = require('./decompress-stock-lz4.cjs');
const original = Buffer.from('Known original stock image fixture\0'.repeat(1024));
const compressed = Buffer.from(lz4.compress(original));
const header = Buffer.alloc(15);
header.writeUInt32LE(0x184d2204); header[4] = 0x6c; header[5] = compressed[5];
header.writeBigUInt64LE(BigInt(original.length), 6);
header[14] = (xxhash.hash(0,header,4,10) >>> 8) & 255;
const checksum = Buffer.alloc(4); checksum.writeUInt32LE(xxhash.hash(0,original,0,original.length));
const frame = Buffer.concat([header,compressed.subarray(7),checksum]);
assert.deepEqual(decompress(frame), original);
const corruptHeader = Buffer.from(frame); corruptHeader[14] ^= 1;
assert.throws(() => decompress(corruptHeader), /header checksum/);
const corruptData = Buffer.from(frame); corruptData[corruptData.length - 1] ^= 1;
assert.throws(() => decompress(corruptData), /content checksum/);
assert.throws(() => decompress(frame.subarray(0,frame.length - 1)), /Truncated/);
const tooLarge = Buffer.from(frame); tooLarge.writeBigUInt64LE(64n * 1024n * 1024n, 6);
assert.throws(() => decompress(tooLarge), /size limit/);
const wrongSize = Buffer.from(frame); wrongSize.writeBigUInt64LE(BigInt(original.length - 1), 6);
wrongSize[14] = (xxhash.hash(0,wrongSize,4,10) >>> 8) & 255;
assert.throws(() => decompress(wrongSize), /output size/);
console.log('PASS stock LZ4 round trip; bad header, checksum, truncation, size and allocation rejected');
